language: bash

jobs:
  include:
    - stage: test
      script: ./build.sh
    - # stage name not required, will continue to use `test`
      #script: ./test 2
    - stage: deploy
      #script: ./deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  deploy_token: $DEPLOY_TOKEN
  travis_token: $TRAVIS_TOKEN
  keep_history: true
  on:
    branch: main
