language: bash

jobs:
  include:
    - stage: test
      script: echo "testing phase"
    - # stage name not required, will continue to use `test`
      script: echo "test passed"
    - stage: deploy
      script: ./build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  deploy_token: $DEPLOY_TOKEN
  travis_token: $TRAVIS_TOKEN
  keep_history: true
  on:
    branch: main
